In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
install_df = pd.read_csv('installments_payments.csv')

In [3]:
install_df.tail(20)

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
13605381,1263000,406628,0.0,45,-808.0,NaN,67.500,NaN
13605382,2263477,443619,1.0,9,-61.0,NaN,5152.095,NaN
13605383,1499195,418486,6.0,22,-412.0,NaN,48635.595,NaN
13605384,2454112,400586,0.0,27,-1720.0,NaN,67.500,NaN
13605385,2239217,451572,0.0,76,-131.0,NaN,46.980,NaN
13605386,1847946,405063,0.0,40,-2057.0,NaN,0.090,NaN
13605387,2630714,441748,1.0,4,-36.0,NaN,14707.125,NaN
13605388,2831819,417123,0.0,8,-15.0,NaN,4399.740,NaN
13605389,2186857,428057,0.0,69,-1532.0,NaN,67.500,NaN
13605390,1829584,450349,1.0,16,-70.0,NaN,18730.350,NaN
13605391,1499195,418486,6.0,32,-112.0,NaN,48635.595,NaN
13605392,2448869,434321,1.0,16,-117.0,NaN,11504.250,NaN
13605393,1285736,434069,0.0,73,-853.0,NaN,67.500,NaN
13605394,1659443,405841,0.0,102,-1888.0,NaN,67.500,NaN
13605395,1499195,418486,6.0,2,-1012.0,NaN,48635.595,NaN
13605396,2186857,428057,0.0,66,-1624.0,NaN,67.500,NaN
13605397,1310347,414406,0.0,47,-1539.0,NaN,67.500,NaN
13605398,1308766,402199,0.0,43,-7.0,NaN,43737.435,NaN
13605399,1062206,409297,0.0,43,-1986.0,NaN,67.500,NaN
13605400,2448869,434321,1.0,19,-27.0,NaN,11504.250,NaN

In [4]:
install_df.shape

(13605401, 8)

In [5]:
curr_app = pd.read_csv('application_train.csv')
y = curr_app['TARGET']
X = curr_app.iloc[:, :1]

In [6]:
X_test = pd.read_csv('application_test.csv')
X_test = X_test.iloc[:, :1]

In [7]:
install_df['DAYS_LATE_PAYMENT'] = install_df.DAYS_INSTALMENT-install_df.DAYS_ENTRY_PAYMENT
install_df['AMT_SHORT_PAYMENT'] = install_df.AMT_INSTALMENT-install_df.AMT_PAYMENT

In [8]:
install_df.head()

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,DAYS_LATE_PAYMENT,AMT_SHORT_PAYMENT
0,1054186,161674,1.0,6,-1180.0,-1187.0,6948.360,6948.360,7.0,0.000
1,1330831,151639,0.0,34,-2156.0,-2156.0,1716.525,1716.525,0.0,0.000
2,2085231,193053,2.0,1,-63.0,-63.0,25425.000,25425.000,0.0,0.000
3,2452527,199697,1.0,3,-2418.0,-2426.0,24350.130,24350.130,8.0,0.000
4,2714724,167756,1.0,2,-1383.0,-1366.0,2165.040,2160.585,-17.0,4.455

In [9]:
gb_sum_df = install_df[['AMT_INSTALMENT', 'AMT_PAYMENT', 'DAYS_LATE_PAYMENT', 'AMT_SHORT_PAYMENT', 'SK_ID_CURR']].groupby('SK_ID_CURR').sum().reset_index()

In [10]:
gb_sum_df['COUNT'] = install_df[['SK_ID_CURR']].groupby('SK_ID_CURR').size().reset_index().iloc[:, 1]

In [11]:
gb_sum_df['AVG_DAYS_LATE'] = gb_sum_df.DAYS_LATE_PAYMENT / gb_sum_df.COUNT
gb_sum_df['AVG_AMT_SHORT'] = gb_sum_df.AMT_SHORT_PAYMENT / gb_sum_df.AMT_INSTALMENT
gb_sum_df['AVG_AMT_SHORT'] = gb_sum_df['AVG_AMT_SHORT'].replace(-np.inf, np.nan)

In [12]:
gb_sum_df.head()

,SK_ID_CURR,AMT_INSTALMENT,AMT_PAYMENT,DAYS_LATE_PAYMENT,AMT_SHORT_PAYMENT,COUNT,AVG_DAYS_LATE,AVG_AMT_SHORT
0,100001,41195.925,41195.925,51.0,0.0,7,7.285714,0.0
1,100002,219625.695,219625.695,388.0,0.0,19,20.421053,0.0
2,100003,1618864.650,1618864.650,179.0,0.0,25,7.160000,0.0
3,100004,21288.465,21288.465,23.0,0.0,3,7.666667,0.0
4,100005,56161.845,56161.845,212.0,0.0,9,23.555556,0.0

In [13]:
gb_sum_df['MISSED_PAYMENTS'] = pd.concat([install_df[['AMT_PAYMENT']].isnull(), install_df[['SK_ID_CURR']]], axis=1).groupby('SK_ID_CURR').sum().reset_index().iloc[:, 1]

In [14]:
gb_sum_df[gb_sum_df.MISSED_PAYMENTS > 0]

,SK_ID_CURR,AMT_INSTALMENT,AMT_PAYMENT,DAYS_LATE_PAYMENT,AMT_SHORT_PAYMENT,COUNT,AVG_DAYS_LATE,AVG_AMT_SHORT,MISSED_PAYMENTS
209,100224,135807.975,135400.230,365.0,205.245,64,5.703125,0.001511,3.0
243,100260,368876.475,359741.475,74.0,9000.000,44,1.681818,0.024398,2.0
880,100926,442790.235,423512.055,312.0,19008.180,45,6.933333,0.042928,4.0
1126,101179,2151927.315,1871308.080,815.0,245090.880,80,10.187500,0.113894,1.0
1163,101216,538286.310,515376.630,393.0,22774.680,85,4.623529,0.042310,2.0
1179,101232,725499.360,720393.345,696.0,5038.515,94,7.404255,0.006945,1.0
1595,101664,485078.490,478006.065,319.0,0.000,41,7.780488,0.000000,1.0
1635,101706,2803830.345,2914384.950,1042.0,-110757.105,138,7.550725,-0.039502,3.0
1869,101949,1550033.640,1534630.050,462.0,9888.705,96,4.812500,0.006380,1.0
2273,102367,709934.895,693089.415,482.0,16642.980,87,5.540230,0.023443,3.0
2381,102478,570050.865,569998.755,504.0,0.000,55,9.163636,0.000000,1.0
2602,102710,220867.920,216035.190,172.0,4697.730,49,3.510204,0.021269,2.0
2929,103054,4477120.380,4454897.895,-615.0,22222.485,153,-4.019608,0.004964,2.0
3021,103153,222704.055,222343.020,175.0,158.535,33,5.303030,0.000712,3.0
3039,103171,1809766.170,1395234.855,380.0,102792.960,68,5.588235,0.056799,1.0
3071,103205,964644.030,960144.030,1814.0,0.000,220,8.245455,0.000000,1.0
3634,103793,2803732.965,1564780.635,948.0,94908.870,83,11.421687,0.033851,23.0
3646,103805,1926974.430,2224695.825,537.0,-297761.175,54,9.944444,-0.154523,1.0
3934,104101,460139.625,114015.375,985.0,0.000,28,35.178571,0.000000,1.0
4066,104235,776008.575,766133.325,-1491.0,9807.750,88,-16.943182,0.012639,1.0
4310,104490,1444454.550,1231845.390,555.0,212588.100,102,5.441176,0.147175,1.0
4341,104523,802730.655,802730.655,265.0,0.000,50,5.300000,0.000000,1.0
4426,104611,1860608.610,1419305.355,697.0,420259.680,129,5.403101,0.225872,1.0
4715,104910,286911.585,286555.275,396.0,153.810,94,4.212766,0.000536,3.0
4856,105061,282109.590,265525.650,1357.0,16381.440,73,18.589041,0.058068,3.0
4934,105144,158276.250,153521.010,73.0,4552.740,37,1.972973,0.028765,3.0
5327,105546,1470845.925,1110006.675,906.0,10035.810,66,13.727273,0.006823,1.0
5716,105948,399485.475,399257.865,228.0,25.110,63,3.619048,0.000063,3.0
5724,105957,931888.980,869638.725,1584.0,56625.255,165,9.600000,0.060764,1.0
6009,106256,420006.105,419781.105,758.0,0.000,40,18.950000,0.000000,1.0
...,...,...,...,...,...,...,...,...,...
326375,442425,1308064.590,680731.515,361.0,80517.915,57,6.333333,0.061555,4.0
326666,442729,2667137.175,1858019.805,-249.0,718598.970,76,-3.276316,0.269427,2.0
327520,443619,595085.895,507465.090,193.0,25548.525,31,6.225806,0.042932,4.0
327749,443858,143288.280,132831.405,377.0,10321.875,60,6.283333,0.072036,2.0
327990,444112,248400.000,248187.645,1023.0,9.855,67,15.268657,0.000040,3.0
328135,444261,33585.120,49365.630,37.0,-16065.630,7,5.285714,-0.478356,2.0
329274,445446,1571349.645,1505516.625,420.0,11541.510,56,7.500000,0.007345,1.0
330153,446376,282496.815,279589.140,626.0,2840.175,36,17.388889,0.010054,1.0
330408,446637,539630.190,525350.790,487.0,13887.900,82,5.939024,0.025736,3.0
330425,446655,90908.730,60475.275,509.0,0.000,15,33.933333,0.000000,1.0
330654,446896,1342688.535,861135.075,-271.0,356003.055,46,-5.891304,0.265142,3.0
330747,446992,525965.400,525778.515,571.0,119.385,87,6.563218,0.000227,1.0
331966,448287,1403550.315,1089934.425,279.0,303095.205,72,3.875000,0.215949,1.0
331968,448289,419645.790,404788.905,206.0,14654.385,56,3.678571,0.034921,3.0
332277,448616,102988.710,79087.500,247.0,23445.000,19,13.000000,0.227646,1.0
332339,448679,4368125.430,3777298.200,375.0,515610.990,180,2.083333,0.118039,2.0
332978,449345,742256.010,724006.800,278.0,18118.710,106,2.622642,0.024410,1.0
333175,449553,186932.880,174952.485,148.0,5525.325,25,5.920000,0.029558,1.0
333312,449697,2075242.275,1666215.405,-698.0,335599.875,88,-7.931818,0.161716,4.0
333934,450349,4600056.600,3781374.210,-192.0,548571.915,181,-1.060773,0.119253,11.0
334189,450613,1323723.015,898458.120,-2266.0,386533.395,135,-16.785185,0.292005,3.0
334612,451057,171376.650,171268.650,579.0,40.500,70,8.271429,0.000236,1.0
335092,451572,347326.830,347196.330,512.0,83.520,98,5.224490,0.000240,1.0
335730,452244,105907.995,96834.105,74.0,8682.390,16,4.625000,0.081980,3.0
336158,452699,845599.140,670478.310,294.0,114985.620,42,7.000000,0.135981,2.0
337108,453692,409180.680,408823.830,1034.0,289.350,152,6.802632,0.000707,1.0
337109,453693,231845.625,211202.910,310.0,20440.215,81,3.827160,0.088163,3.0
337221,453810,183867.705,170858.070,178.0,12784.635,21,8.476190,0.069532,1.0
337588,454195,94243.185,90867.870,39.0,3375.000,20,1.950000,0.035812,1.0
339310,455973,254798.055,250115.715,64.0,0.000,15,4.266667,0.000000,1.0

In [15]:
X = X.merge(gb_sum_df, on='SK_ID_CURR', how='left')
X_test = X_test.merge(gb_sum_df, on='SK_ID_CURR', how='left')

In [16]:
corrs = pd.Series([y.corr(X[col]) for col in X.columns[-gb_sum_df.shape[1]+1:]], index=gb_sum_df.columns[1:]).sort_values()

In [17]:
corrs = abs(corrs).sort_values(ascending=False)
corrs

AVG_AMT_SHORT        0.052735
DAYS_LATE_PAYMENT    0.030351
AMT_SHORT_PAYMENT    0.027326
AMT_PAYMENT          0.024375
COUNT                0.021096
AVG_DAYS_LATE        0.020916
AMT_INSTALMENT       0.019811
MISSED_PAYMENTS      0.017438
dtype: float64

In [18]:
X[corrs.index].to_pickle('features_install.pkl')
X_test[corrs.index].to_pickle('features_install_test.pkl')